### ISSUE TITLE
[Spec] - Image: Typography

### ISSUE THREAD

**Issue by matthew-carroll** [Flutter-Bounty-Hunters/swift_ui#13]
Investigate the `Image` view to determine if there are any typography behaviors. If there are, add examples to the Swift UI gallery app, and then add details to the `Image` spec.

**Comment by suragch** [comment]
There are a few constructors that take a `label` parameter, which is of type `Text`. This is an example:

```
Image("flutter", label: Text("hello"))
```

However, the [docs](https://developer.apple.com/documentation/swiftui/image/init(_:bundle:label:)) say this about label:

> The label associated with the image. SwiftUI uses the label for accessibility.

As far as I can tell, there is no visual effect for the label:

<img width="159" alt="flutter image with label" src="https://github.com/Flutter-Bounty-Hunters/swift_ui/assets/10300220/e34afdde-ffae-4e84-b3d7-575be6f3dc24">

So I think we can close this issue.

**Comment by matthew-carroll** [comment]
Thanks for looking into it. I'll close this ticket. Please update the spreadsheet. CC @vincevargadev on the accessibility part.
