### ISSUE TITLE
[Spec] - VStack, HStack, ZStack: Typography

### ISSUE THREAD

**Issue by matthew-carroll** [Flutter-Bounty-Hunters/swift_ui#14]
Investigate the `VStack`, `HStack`, and `ZStack` views to determine if there are any typography behaviors. If there are, add examples to the Swift UI gallery app, and then add details to the appropriate spec.

I doubt there are any typography requirements, which is why I've grouped the views together. If it turns out to be more complicated, we can re-assess.

**Comment by suragch** [comment]
I don't see any typography requirements for [VStack](https://developer.apple.com/documentation/swiftui/vstack), [HStack](https://developer.apple.com/documentation/swiftui/hstack), or [ZStack](https://developer.apple.com/documentation/swiftui/zstack).

**Comment by matthew-carroll** [comment]
Thanks for checking. Can you mark those areas of the spreadsheet as N/A?
