### ISSUE TITLE
[Gallery][Layout] - Create examples for VStack, HStack, and ZStack

### ISSUE THREAD

**Issue by matthew-carroll** [Flutter-Bounty-Hunters/swift_ui#16]
Investigate the APIs for `VStack`, `HStack`, and `ZStack` for layout behaviors. Add a full range of layout examples to the Swift UI gallery app, demonstrating everything they can do.

**Comment by SumanHansada** [comment]
Hi @matthew-carroll .. Shall I assign this to myself?

**Comment by matthew-carroll** [comment]
I just assigned it to you. Please let me know if you have any questions about it. Thanks.

**Comment by matthew-carroll** [comment]
@SumanHansada how's this coming along?

**Comment by SumanHansada** [comment]
Hi @matthew-carroll, I had pinged you regarding a doubt on Discord channel. Going onwards I will update here..
I was going through the swift examples of VStack and HStack.
Suppose the example of VStack, By default we have examples of top, middle and bottom and there spacer is used to align it.
However, VStack has their own alignment property, which aligns the item inside VStack in leading, Center or Trailing position. Are we also creating the layout for these? Same goes for HStack as well. 
Reference - https://developer.apple.com/documentation/swiftui/alignment
| **Leading Alignment** | **Center Alignment** | **Trailing Alignment** |
| ---------------------- | ---------------------- | ----------------------- |
| <img width="434" alt="image" src="https://github.com/Flutter-Bounty-Hunters/swift_ui/assets/9078433/2e5609e7-09d4-4149-a512-1bf1445b9704"> | <img width="434" alt="image" src="https://github.com/Flutter-Bounty-Hunters/swift_ui/assets/9078433/8e2d8bef-ca18-4e83-99cf-4d182fd1af54"> | <img width="434" alt="image" src="https://github.com/Flutter-Bounty-Hunters/swift_ui/assets/9078433/aaa90bbb-3ed6-4629-9b39-3136d99b65de"> |

**Comment by matthew-carroll** [comment]
Hi @SumanHansada - we'd like to capture pretty much every configuration of those layout widgets. Please go ahead and use whatever seems like the most appropriate way to accomplish the layout goals. Also, please add as many more examples as needed to exhaust the available properties. Let me know if you have further questions.

**Comment by matthew-carroll** [comment]
@SumanHansada can you provide an update on this?

**Comment by SumanHansada** [comment]
Hi @matthew-carroll,
Added examples of VStack, Please review it.. 
https://github.com/Flutter-Bounty-Hunters/swift_ui/pull/21
Adding HStack and ZStack as well.

**Comment by SumanHansada** [comment]
Hi Matt,

I have raised one PR, please review it.. I will raise ZStack and HStack
Saturday or Sunday.

Regards,
Suman

**Comment by matthew-carroll** [comment]
I'm currently implementing `VStack`, `HStack`, and `ZStack`. I'll add demos as needed. Closing this.
