### ISSUE TITLE
[Spec] - Text: Typography

### ISSUE THREAD

**Issue by matthew-carroll** [Flutter-Bounty-Hunters/swift_ui#5]
Research the Text view for typography, add relevant Swift UI examples, and add spec details to the relevant Wiki page.

**Comment by suragch** [comment]
Can you link to a good spec example that I can model the typography spec after. It doesn't need to be about typography or even SwiftUI. I'm just not really sure about how to write it or what to include.

**Comment by matthew-carroll** [comment]
I'm not sure that I have any good reference for the specific way that we're breaking down examples and spec's.

I started a `Text` view case study before we got the UX Leads selected. The following write-up isn't quite in the correct voice for what we now want from UX Leads, but hopefully this helps guide some of what you're doing: https://github.com/Flutter-Bounty-Hunters/swift_ui/wiki/Case-Study:-Cloning-Swift-UI's-Text-view

From a first principles perspective, the question is, from an API design and code implementation standpoint, what would a developer need to know about your UX area to effectively implement the desired behavior?

If you wanna take a crack at it, we can always move through a few revisions until we get something that works.

**Comment by suragch** [comment]
Thanks. I'll take a crack at it. It'll probably be early next week before I publish, though. Should the wikis also be in the form of a PR? I've never written a GitHub wiki before.

**Comment by matthew-carroll** [comment]
> Should the wikis also be in the form of a PR?

Nope - you can just edit the Wiki page directly. I recommend writing your content first and then pasting it into the page just in case other developer are editing the same page at the same time.

**Comment by suragch** [comment]
I started the spec. The details are pretty deep but so far I've divided it into sections and I'll work on filling out the TODOs. Let me know if I'm headed in the wrong direction.

**Comment by matthew-carroll** [comment]
@suragch it looks like a good start. I think it would be helpful to see Swift UI examples along with the pure typography descriptions. For example, when describing types of system fonts and the use of other fonts, it would be helpful to see how to specify different fonts in a `Text` view.

The output of all the UX descriptions will be a Flutter API design. That Flutter API design will need to account for the existing Swift UI API design. If we capture the Swift UI APIs in the UX descriptions, then that will make it easier to synthesize a Flutter API.

Please let me know if you have any questions before you continue with the spec.

**Comment by suragch** [comment]
That's good to know that about including SwiftUI code examples. I wasn't doing it previously because I thought it was the Flutter spec and I didn't know what the API was. Now I understand. I'll add them in.

**Comment by suragch** [comment]
I'm finished writing the typography specs. Let me know if any further changes are needed.

**Comment by matthew-carroll** [comment]
Thanks @suragch - I appreciate you documenting so much detail. Here are some comments based on what I'm seeing in the spec.

> Flutter also has the notion of pixel density independent font sizes. However, it shouldn't be assumed that SwiftUI point sizes and Flutter fonts size values are the same. If any conversion needs to happen, this SwiftUI port should ensure that the size values produce the same sized font on the screen.

Can you dig into this? The details to implement the right solution in Flutter isn't necessarily a typography domain issue, but I think an understanding of the differences in manifest behavior between Swift UI and Flutter would still fall under the typography domain.

Re: Font Design

Can you elaborate more on font design? This seems like an unusual property. I'm not familiar with such a thing in Flutter or on the web. There are, of course, default fonts on the web that are identified by their characteristics of serif, sans-serif, monospace, etc., but I'm not familiar with control over a property called "font design".

Re: Font Widths

I'm not sure that the brief mention is actionable. Are these fonts that are being dynamically stretched, or is the "font width" operating as a selector among a family of related fonts?

> You can set the text foreground style using foregroundStyle. This takes a ShapeStyle, which can be a system color:

Can you mention why it's a `ShapeStyle`? Text seems like a strange thing to think of as a shape. Are there any implications of this? Anything weird that a `ShapeStyle` can do, which we wouldn't normally associate with text styling?

> Or a material:

What's a material? How does it work?

Re: Background

Did you check for behaviors regarding multiline text, especially multi-line text where the text size changes along the way? Also, is there some affordance for padding or other spacing manipulation where the background paints?

Re: Predefined text styles

I'm not sure this is actionable, for two reasons. First, we don't have any of the specific property values for each predefined style. Second, you mentioned that they depend upon dynamic type, accessibility, and platform. We'll need to specify each of the property values for each of those factors.

**Comment by matthew-carroll** [comment]
Thanks. Just to confirm, did you add those to the spec? I scrolled through and I think I saw some updates, but wanted to confirm that these details were added.

**Comment by suragch** [comment]
> Just to confirm, did you add those to the spec?

I hadn't since I didn't know how your response would affect it, but I've updated the spec now.

**Comment by matthew-carroll** [comment]
Thanks. I'll go ahead and close this issue. More questions will probably come up during API analysis and implementation, but we can handle those on a case by case basis. Please feel free to start looking into other primitive widgets in a similar fashion. For example: Image, VStack, HStack, ZStack.

It's possible that none of those even have typography considerations, but we'll need to investigate first to make sure, and then mark the spreadsheet accordingly.

**Comment by Maatteogekko** [comment]
@suragch I stumbled upon [this PR](https://github.com/flutter/flutter/pull/137275), which is available on flutter master. I thought you would like to have a look
