### ISSUE TITLE
[Spec] - Text: Typography: Attributed strings

### ISSUE THREAD

**Issue by suragch** [Flutter-Bounty-Hunters/swift_ui#8]
Create a full range of examples to demonstrate Swift [attributed strings](https://developer.apple.com/documentation/foundation/attributedstring) displayed in a Text view. These will be a part of the [Text primitive portion of the SwiftUI gallery app](https://github.com/Flutter-Bounty-Hunters/swift_ui/tree/main/doc_swift_ui_gallery/swift_ui_gallery/swift_ui_gallery/primitives/text/typography).

**Comment by matthew-carroll** [comment]
I'm closing all spec tickets in favor of direct development based on example observation and documented Swift UI properties.
